---
:concurrency: 31
staging:
  :concurrency: 31
production:
  :concurrency: 31
:queues:
  - default
  - mailers
  - custom_report
  - now_scan_1
  - now_scan_2
  - scheduled_scan_1
  - scheduled_scan_2
  - free_shodan_scan
  - free_virus_total_broker
  - brokers
  - sync_nvd_base
:limits:
  default: 1
  mailers: 2
  custom_report: 1
  now_scan_1: 2
  now_scan_2: 2
  scheduled_scan_1: 4
  scheduled_scan_2: 14
  free_shodan_scan: 1
  free_virus_total_broker: 1
  brokers: 2
  sync_nvd_base: 1
